// <auto-generated />
using System;
using ECommerce.DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.EntityLayer.Concrete.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat1name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat2name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat3name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cat4name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingcat1name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingcat2name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingcat3name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingcat4name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("newprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlcat1name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlcat2name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlcat3name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlcat4name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("width")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ws_code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
